### ISSUE TITLE
change run command semantics?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#1030]
Restarts are needed far more often than cold starts but cylc implicitly assumes that cold starts are more important.  This is particularly obvious when using Rose: if you accidentally use the default `rose suite-run` the resulting cold start wipes out your suite state and prevents going back to the intended restart.

So I propose we drop `cylc restart` and have `cylc run` automatically do a restart if prior state exists, a cold start if it doesn't, and an option to force a cold start even if a restart is possible.  This simplifies our command set a bit, and it is safe because an accidental restart is not destructive. It is easy to deprecate too: `cylc restart` will be an alias for `cylc run --restart` which will abort if a restart is not possible.

@dpmatthews - can you give Met Office perspective on this?

**Comment by kaday** [comment]
`cylc run --new` may need a `This deletes the logs. Are you sure?` or added/different functionality.
@dpmatthews I hope this covers what we discussed following user feedback and is in the correct place.

**Comment by kaday** [comment]
A user has commented that having a `cold-start` as default for the run option when they are restarting a suite has nearly caused the deletion of data. I think issue will/should capture and help safe-guard against this.

**Comment by benfitzpatrick** [comment]
We could have a new command that is incremental by default (but detects when a suite has run to completion) with an option to force a new run. `cylc run` as an alias with a new run option by default.

**Comment by benfitzpatrick** [comment]
After #1885.

**Comment by wxtim** [comment]
I've been looking at this as part of my work on planning the transfer of functionality from rose to cylc.
As part of that work I've been looking at what I want the new command (provisionally called `cylc flow`) which will replace `rose-suite-run` to do.

I am unhappy with the word "restart" because to me I hear the words "from the beginning" immediately afterwards. I feel that the word "continue" would better describe what this means. Having said this, I am disinclined to change the usage of this word because I think this would cause confusion.

At the moment my proposal for the `cylc flow` command contains the following suggestions - 
 Restart a suite from last checkpoint (`--restart`, `--continue`).
* Restart a suite at a given checkpoint (`--restart-from`, `--restart-at`,
  `--continue-from`).
* Restart a suite from an arbitary point (warm start, `--warm-start`,
  `--restart-from`, `--continue-from`).
* Cool start - start a suite from the beginning without cleaning install or
  rebuilding. (`--restart-at BEGINNING`, `--dc-al-coda`?)
* Cold start a suite - start a suite from the beginning carrying out build
  tasks (`--rebuild`) but not necessarily cleaning any logs.
* Clean start a suite - start a suite having cleaned out any data generated
  (`--clean`) but not carrying out a full rebuild.
* Both of the above at once?
* Increment start a suite - start a new, clean, experimental iteration with
  different data location but perhaps sharing some compiled material from
  cold start (`--increment`, `--increment PATTERN`)? If you had
  `cylc flow --increment --name MyExperiment` you'd get suites `MyExperiment_0`,
  `MyExperiment_1`... and so on.


Another way of looking at this would be :
<table>
<tr>
<td colspan=2 rowspan=2></td><td colspan=2>Clean the installed files</td>
</tr><tr>
<td>yes</td><td>no</tr>
</tr><tr>
<td rowspan=2>Start suite from the beginning</td><td>yes</td><td>clean-run or increment</td><td>cylc flow</td>
</tr><tr>
<td>no</td><td>Is this desirable? <br> might you want a clean "warm start"<br> to remove corrupted files?</td><td>"restart" or "continue" from checkpoint<br>"Warm start" from arbitary point</tr>
</table>

**Comment by dpmatthews** [comment]
I think it's clear we'll need to give this a lot of thought and will need a proposal document to fine tune the detail.

**Comment by wxtim** [comment]
@TODO - create a proposal document in cylc-admin

**Comment by oliver-sanders** [comment]
Agreed at CylcCon2020

Superseeded by #3897
