### ISSUE TITLE
Kill job on task state reset from submitted or running

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc-flow#2621]
From #2528.

When users reset the state of a submitted or running task to ready without killing the original job first can lead to existence of multiple jobs of the same task. This should also be handled correctly. We should have the suite make an automatic attempt to kill the original job when user resets the state of a submitted or running task.

Somewhat related (although not a submit number issue): careless (but common) use of suicide triggers can result in removing an active task proxy. Currently we just log a warning about this; we should probably kill the active job as well.

See:
https://github.com/cylc/cylc/issues/2528#issuecomment-359076831
https://github.com/cylc/cylc/issues/2528#issuecomment-359081219
https://github.com/cylc/cylc/issues/2528#issuecomment-359081543

See also: #2199 #2394 #2506 #2618

**Comment by hjoliver** [comment]
(It's arguable that this is a bug IMO, although I agree that attempting to kill the original job is preferable anyway).

**Comment by matthewrmshin** [comment]
To further improve the issue reported in #2528, the logic for job 2 submission should check that job 1 is no longer running. It can then decide to either:
* fail job 2 submission, or
* kill job 1, then submit job 2.

**Comment by dpmatthews** [comment]
To be safe, I think that if you try to trigger or reset the state of a submitted or running task then, by default, this should fail. We would then need a force mode to override this.

**Comment by dwsutherland** [comment]
Perhaps a warning prompt/messaged could be issued/logged (just the GUI? interactive CLI?) on task reset/trigger before kill of found running/submitted job(s). 

This could be achieved via an optional request argument (Default; 'cancel_job=True' (kills existing running/submitted job)) when set to False will include a warning message in the response and not kill... 

What to do on failure to kill job 1?
If job 1 is stuck and you continue with job 2, then messages from job 1 could still be received by the suite when unstuck/manual-kill (unless this behavior has been changed since 7.5.0)

**Comment by matthewrmshin** [comment]
In 7.7+ messages from old jobs are ignored.

**Comment by matthewrmshin** [comment]
The only problem left is that job 1 may continue to occupy the same computing resource that job 2 will require - causing job 2 to fail eventually.

**Comment by oliver-sanders** [comment]
Also closed by #3515
