### ISSUE TITLE
Inheritance parsing - ignoring items if not all quoted

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc-flow#2700]
Bit of a weird one - only hit it because of working with parameterization.

Have written task inheritance in two ways. In the first, the non-quoted item doesn't get picked up:

inherit = 'MAINFAM<major, minor>', SOMEFAM

Whereas when each item is quoted in the list the do all get picked up:

inherit = 'MAINFAM<major, minor>', 'SOMEFAM'

Had to put MAINFAM, in quotes because of the need to (according to validation) with two items to iterate over - presumably to identify it as a single item. You can replicate this behavior with non-parameter based inheritance though (although it would be odd to quote an item if you didn't need to for parameterization):

inherit = 'BIGFAM', SOMEFAM

Depending on the rest of your suite graphing and runtime you may or may not miss that the SOMEFAM type entry gets missed.

**Comment by matthewrmshin** [comment]
Does it work if you don't quote anything?

**Comment by arjclark** [comment]
Potentially anticipating your next question, you also can't do (which is closer to my real use-case rather than the simplified one above):

 'MAINFAM<major, minor>, SOMEFAM<minor>'

as it only expands out the first MAINFAM item but not the SOMEFAM one (still reads it as SOMEFAM<minor> and errors validation as: [FAIL] 'ERROR, undefined parent for coupled_m1_s01: MAINFAM_m1_s01, SOMEFAM<mem>')

**Comment by arjclark** [comment]
Further experimenting also shows another expansion issue with:

**Comment by arjclark** [comment]
Further experimenting also shows an issue with: `inherit=MAINFAM_M<major>_S<minor>`, as this also fails to expand out the second item as: 

`ERROR, undefined parent for ... : MAINFAM_M1_S<step>`

@matthewrmshin - would you like me to capture that in a separate issue or just leave it in here as the two are (presumably) inter-related?

**Comment by kinow** [comment]
The problem is in the `validate.py`, the regex used for `'BIGFAM', SOMEFAM` is `'([^'\\]*(?:\\.[^'\\]*)*)'`.

Follow [Pythex link](https://pythex.org/?regex=%27(%5B%5E%27%5C%5C%5D*(%3F%3A%5C%5C.%5B%5E%27%5C%5C%5D*)*)%27&test_string=%27BIGFAM%27%2C%20SOMEFAM&ignorecase=1&multiline=1&dotall=1&verbose=0) to see that the match finds `BIGFAM` and then just gives up on `SOMEFAM`.

The naive solution, I think, would be to just add more to that regex and increase its complexity, but thus allowing it to find matches of single-quoted, plus non-quoted values.

But then the issue would be whether mixing quotes would be OK too. i.e., is this valid?

```
inherit = "BIGFAM", 'SOMEFAM', FAM
```

Unit test to reproduce the issue:

```python
import unittest
import tempfile

from cylc.config import SuiteConfig


class TestConfig(unittest.TestCase):

    def test_inheritance(self):
        template_vars = {}
        with tempfile.NamedTemporaryFile() as tf:
            tf.write("""
[scheduling] 
    [[dependencies]] 
        graph = '''hello => BYE
                   hello => CIAO
        ''' 
[runtime] 
    [[hello]] 
    [[BYE]] 
    [[CIAO]] 
    [[ goodbye_0 ]] 
        inherit = 'BYE', CIAO
            """)
            tf.flush()
            config = SuiteConfig('test', tf.name, template_vars=template_vars)
            self.assertTrue('goodbye_0'
                            in config.runtime['descendants']['BYE'])
            self.assertTrue('goodbye_0'
                            in config.runtime['descendants']['CIAO'])
```

It will fail in the last `assertTrue`, due to `CIAO` being missing in the list of nodes with descendants.
