### ISSUE TITLE
cylc review: No suites found when using a different run directory

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3118]
Hi,

I had some old testing configuration in my $work computer. It had the run and work directories of localhost set to `/tmp/run` and `/tmp/work` respectively.

Executed a suite and noticed that it did not appear in Cylc Review. I think [Cylc Review is not using Cylc's code that handles the logic to locate the suites](https://github.com/cylc/cylc/blob/cd716fcd834828aa03bb8e368ccebd0d30497149/lib/cylc/review.py#L736).

**Comment by hjoliver** [comment]
As noted on Riot - this probably dates to `cylc review` origins in Rose, which I think requires/assumes the standard run dir location, with `rose suite-run` having the ability to symlink sub-directories to other locations instead ... but in cylc now, this is a bug.

What to do about it?  For cylc-8 and migration of `rose suite-run` to cylc, it might be best to take the rose approach: standard suite run dirs only, with automatic symlinking underneath.  For 7.8.x I'm not sure  if the `cylc review` service could read Cylc site and user global config - better wait for input from the UK team on this.

**Comment by kinow** [comment]
>For cylc-8 and migration of rose suite-run to cylc, it might be best to take the rose approach: standard suite run dirs only, with automatic symlinking underneath.

I thought it would be easier to fix this one by accessing the site/global config for Cylc 8 and later. Is there a reason why we need the symlink? (I remember a recent bug in 7.8.x that was about symlinks too, and I think it was in NIWA environment for Cylc review? But could be wrong)

>For 7.8.x I'm not sure if the cylc review service could read Cylc site and user global config - better wait for input from the UK team on this.

Roger.

**Comment by hjoliver** [comment]
Let's see what @matthewrmshin et. al., say, but I *think* the symlink approach is arguably better because other users and support people, and third party tools (which Rose Bush sort of was) can *always* find suite output under `$HOME/cylc-run/SUITE` even if the data actually happens to reside elsewhere on disk thanks to the symlink.  Otherwise, other tools have to know how read cylc global config files.

Actually, worse news for the "read global config" approach: on our new HPC (and this sort of access restriction is likely to become the default) `cylc review` will only be allowed to read files from a special "suite log" partition, not user home dirs (and the suites will again put logs in that location via a symlink  `$HOME/cylc-run/SUITE/log`).

**Comment by matthewrmshin** [comment]
Yes. The history is that in the world of SCSUI (and friends), users were able to customise locations too easily, but suites (jobs) have all come to a single set of consensus. A few users would defy that common approach and customise, leading to difficulties when they require support.

The Rose approach was an attempt to compromise. Users can still customise, but the system will insist on adding a symbolic link from HOME to make it easier for us support teams.
