### ISSUE TITLE
Upgrade alert

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc-flow#3400]
**Describe exactly what you would like to see in an upcoming release**

There are 2 parts:
1. The UI should inform/alert users when a new stable release of Cylc is available to use on site.
   * The UI should offer users an easy route to upgrade.
   * Similarly, the UI should inform users of new test releases of Cylc, and offer users an easy way to test out the new release.
   * Users are currently reliant on deployment/development team to chase them to upgrade.
2. A running workflow should be aware of its source (e.g. version control system or package management system) and inform/alert the user if they are currently running an out-of-date version of the workflow.
   * In a recent conversation, a user told me that they have **forgotten to reload their suite** after doing some development and committing the changes 2 months ago.
   * The [rose suite-cmp-vc](https://github.com/metomi/rose/blob/master/bin/rose-suite-cmp-vc) command is a poor-person's way to address this problem.
   * Is there anything modern CI/CD principles can teach us when it comes to helping users manage their suites?

**Additional context**

I am sure we have discussed this offline in the past, but I don't recall ever raising an issue. A recent conversation with a user has reminded me of this. Aspects of this issue are UI and deployment issues, so please feel free to move this around.

**Pull requests welcome!**

**Comment by kinow** [comment]
Oh, yes, like Riot.im does when there is a new version. It must be interesting to implement this on both frontend and backend.

**Comment by oliver-sanders** [comment]
Migrating this as it is a UI issue.

The first part can be addressed with a "click here to update" button (which really just refreshes the page).

The second part should be solved with the visualisation of source directories in the UI: https://github.com/cylc/cylc-ui/issues/548. Currently I'm thinking we could display a blue dot or similar (like the Rose Edit GUI) next to run directories which have drifted from the source. At present this issue is looking a little bare but expect some more sketches, ideas and discussions in due course.
