### ISSUE TITLE
conf: ensure all proposed changes have been enacted

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3696]
Ensure all changed document in the [config change proposal document](https://cylc.github.io/cylc-admin/proposal-config-changes.html) have been implemented pre 8.0.0 release.

**Pull requests welcome!**

**Comment by wxtim** [comment]
- [ ] [authentication] -> obsolete
- [ ] [cylc][events]mail * -> [scheduler][mail]
- [ ] [cylc][events] -> [scheduler][events]
- [ ] [cylc]task event mail interval -> [scheduler][mail]task event batch interval
- [ ] [cylc]health check interval -> [scheduler]health check interval
- [ ] process pool * -> [scheduler]process pool *
- [ ] [documentation] -> obsolete
- [ ] [document viewers] -> obsolete
- [ ] [suite logging] -> [scheduler][logging]
- [ ] run directory rolling archive length -> [scheduler]run directory rolling archive length
- [ ] [task events]mail smtp -> obsolete
- [ ] [task events]mail retry delays -> obsolete
- [ ] [suite servers] -> [scheduler]
- [ ]     [suite servers]auto restart delay -> [scheduler]auto restart delay
- [ ]     [suite servers]run hosts -> [scheduler][run hosts]available
- [ ]     [suite servers]condemned hosts -> [scheduler][run hosts]condemned
- [ ]     [suite servers]run ports -> [scheduler][run hosts]ports
- [ ]     [suite servers]ranking -> [scheduler][run hosts]ranking
- [ ] [suite host self-identification] -> [scheduler][host self-identification]
- [ ] [job platforms] -> [platforms]
- [ ] [job platforms][]task communication method -> [platforms][]communication method
- [ ] [cylc]UTC mode -> [scheduler]UTC mode
- [ ] [editors]
- [ ] Discussed at CylcCon. Agreed to keep these settings but discourage their use. Also, change them to use to $EDITOR & - [ ] $GEDITOR if set (otherwise use current defaults).
- [ ] disable interactive command prompts -> obsolete
- [ ] [test battery] -> obsolete
- [ ] [job platforms][]batch system -> [platforms][]job runner
- [ ] [job platforms][]batch submit command template -> [platforms][]job runner command template
- [ ] [job platforms][]task event handler retry delays -> obsolete
- [ ] [job platforms][]scp command -> obsolete
- [ ] No longer used. Also remove the cylc [util] scp-transfer command.

**Comment by MetRonnie** [comment]
Might be a good idea to add our names next to items in the checklist when we start working on them, to avoid two people doing the same one

**Comment by wxtim** [comment]
@hjoliver  - Was there a reason that you closed this issue?

**Comment by hjoliver** [comment]
:confounded: sorry @wxtim that was definitely accidental.

**Comment by MetRonnie** [comment]
> `[cylc]health check interval` -> `[scheduler]health check interval`

This seems to be entirely missing from global config. Anyone know what happened to it? @wxtim ?

**Comment by oliver-sanders** [comment]
Ah yeah, leave it as `[scheduler][main loop][health check]interval`.

**Comment by wxtim** [comment]
So I think that's everything which isn't blocked!

**Comment by MetRonnie** [comment]
Oops, I still need to do #3910

**Comment by hjoliver** [comment]
> So I think that's everything which isn't blocked!

Wow that was a load of PRs, well done :bouquet:

**Comment by wxtim** [comment]
- [x] Create change guide in docs - pass to issue https://github.com/cylc/cylc-doc/issues/170

**Comment by oliver-sanders** [comment]
https://github.com/cylc/cylc-flow/issues/4034

**Comment by MetRonnie** [comment]
I've unticked
> [editors] - discussed at CylcCon. Agreed to keep these settings but discourage their use. Also, change them to use to $EDITOR & $GEDITOR if set (otherwise use current defaults).

because we haven't discouraged their use or set them to use `$EDITOR` or `$GEDITOR` by default

**Comment by oliver-sanders** [comment]
> because we haven't discouraged their use or set them to use $EDITOR or $GEDITOR by default.

Was done by https://github.com/cylc/cylc-flow/pull/3692

**Comment by MetRonnie** [comment]
Ah ok, is the "if unspecified Cylc will use $(G)EDITOR" spiel enough to consider their use discouraged?

**Comment by oliver-sanders** [comment]
I think the "discourage use" was more aimed at the `[editors]` section

**Comment by oliver-sanders** [comment]
for
