### ISSUE TITLE
Test Battery using global.cylc not global-tests.cylc

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-flow#3697]
When running functional tests, it appears to be selecting the <del>flow.rc</del> global.cylc as the config file, rather than the usual <del>flow-tests.rc</del> global-tests.cylc.

To reproduce...put some invalid items in global.cylc file and run a functional test. I would expect it to ignore the global.cylc and select congif file global-tests.cylc

**Screenshots**

![image](https://user-images.githubusercontent.com/37735232/87803164-0aa5e200-c84a-11ea-938c-da3806fae3d4.png)

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by MetRonnie** [comment]
I don't think it is actually using the <del>flow.rc</del> global.cylc file in the tests - I think some line of code is calling `cylc get-global` for whatever reason, and thus it raises the error if global.cylc is invalid. But (if it is valid and no error is raised), it doesn't actually get used.

E.g. `tests/f/restart/52-cycle-point-time-zone.t` depends on `[cylc]UTC mode` being `False`. If you:
1. Go into `tests/f/restart/52-cycle-point-time-zone.t` and get rid of the `UTC mode = False` line 
2. Set the contents of global.cylc to

    ```
    [cylc]
        UTC mode = True
    ```
3. Make sure global-tests.cylc is empty or doesn't have `UTC mode` set in it

then the test will still pass because UTC mode defaults to False.
