### ISSUE TITLE
checkpoint: re-evaluate purpose of checkpointing

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3864]
Cylc supports database checkpointing, which, in practice involves making a complete copy of the data in certain tables of the database at a certain point in time. The workflow can then be restarted from any pre-recorded checkpoint.

In effect this enables us to wind back the task pool to a previous state. Off the top of my head the use cases for this are:

1. Allowing rollback of user-intervention e.g. `cylc reset`, and its impacts e.g. suicide triggers.
2. Allowing rollback of reload.
3. Providing an interface for re-running recent tasks e.g. in response to corrupted data.
4. Others?

Checkpointing is not the nicest thing, it leaves us with duplicate tables, extra load/dump logic, CLI commands and complexity. I'm not entirely sure what purpose it is intended to serve, since SoD the use cases I can think of have been somewhat eroded:

1. This should be achievable via other means.
2. Task outputs are recorded in the DB allowing clean handing of previously destructive graph changes.
3. Since SoD reflow provides a more targeted interface for this.

I'm not sure I really understand the purpose of checkpointing and I don't think that checkpointing is well understood even by advanced users (or developers 😆).

It's worth re-evaluating checkpointing in the post SoD world now that we have removed Cylc7 restart compatibility to see if there are any remaining use cases. If we can't think of any its time to reach out to users to see if they have any we're not aware of.

**Comment by oliver-sanders** [comment]
This #3863 will break checkpoint functionality somewhat as task outputs would not be subject to checkpoint logic.

If the resolution of this issue is that we need to keep checkpoint logic then this issue can be closed once the task outputs table is correctly checkpointed.

See https://github.com/cylc/cylc-flow/pull/3863#discussion_r503987411

**Comment by oliver-sanders** [comment]
PS:

I wondered whether it would be possible to get sqlite3 to preserve its transaction record to enable a more global checkpoint functionality, however, after a scan through the docs I don't think that's possible, though there is some related functionality.

**Comment by hjoliver** [comment]
> I'm not sure I really understand the purpose of checkpointing and I don't think that checkpointing is well understood even by advanced users (or developers laughing).

The primary and original use case is normal restart, which you seem to have excluded from your list above for some reason? Even though restart requires the latest/current DB, it is still a checkpoint because the DB records run history as well as the ever-changing current scheduler state.

Then (secondary use case) once you maintain a "current state" checkpoint for restarts, it is easy to allow users to take and record other checkpoints at will, at points in the workflow that they think they might need to roll back to.

However, I'm not aware of anyone who actually uses checkpointing like that.  They probably just do a crude cycle point warm start instead.  And I agree that SoD reflow probably supersedes that use case.  But what about restart?

I'm not really concerned about duplicate tables, because its only duplicating "current state" snapshot tables, not the ever-growing tables that record run history.  BUT that said we should remove the capability if it is not used and we now have better options.

**Comment by oliver-sanders** [comment]
> But what about restart?

Can't we just restart from the non-checkpoint tables?

**Comment by hjoliver** [comment]
Not as they are because they record the history of the whole run, not just the current state of the scheduler (which gets continually updated as things change, rather than growing forever). Pretty sure restart has always been a checkpoint table, long before we added the ability to take other checkpoints as well.

**Comment by oliver-sanders** [comment]
> But I presumed you wanted to get rid of the task_pool table too

Er, no, we definitely want to keep that one!

**Comment by hjoliver** [comment]
I've always thought of the `task_pool` table as the "latest" checkpoint, which we update whenever something changes.  

We're both right, it's just semantics! But at least now I understand you don't want to remove that table as well.  Let's chalk that entire discussion up to a misunderstanding. :rofl: 

In that case, yes I think we can remove the (named) checkpoint tables and associated CLI etc.

**Comment by hjoliver** [comment]
In principle reflow isn't a drop-in replacement for checkpoint restart, because the checkpoint could record a complex state of the flow that isn't easy to reproduce by triggering one or a few tasks at the top of a reflow.  However in practice it should be OK because I doubt that messy checkpoints would be of any use in reality.  You have to plan checkpoints in advance so should choose a simple bottleneck in the flow to do it.

If the scheduler is already up, reflow is a no-brainer (`cylc trigger --reflow ...`).

If it the scheduler is stopped though, it's a little trickier:
- start the scheduler via cold, warm, or restart
- stop the main flow
- trigger the reflow from your desired "checkpoint" location

To make it easier we should support this:
- warm start the scheduler at the cycle point of the desired reflow, with an empty task pool
- automatically trigger the first reflow task(s)

Actually, by that sort of mechanism reflow would allow us to `cylc play` from any arbitrary point in the graph :boom: that could be useful!

**Comment by hjoliver** [comment]
Note we also use automatic named checkpoints before and after a reload, as a safety net:
```python
$ git grep '\.checkpoint('
cylc/flow/scheduler.py:        self.suite_db_mgr.checkpoint("reload-init")
cylc/flow/scheduler.py:                self.suite_db_mgr.checkpoint("reload-done")
cylc/flow/scheduler.py:        return self.suite_db_mgr.checkpoint(name)
```

**Comment by hjoliver** [comment]
## Decision: remove named checkpointing

- no users have replied in favour of named checkpointing on the Discourse thread
- @oliver-sanders, @hjoliver  and @dpmatthews  have agreed we can remove it

I'll supersede this issue with one for the removal...
