### ISSUE TITLE
validate: add separate option for cyclic graph detection

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#3869]
Cyclic graph validation can be quite slow and is currently included as part of  `--strict`.
See https://github.com/cylc/cylc-admin/pull/111#discussion_r503579388
See also https://github.com/cylc/cylc-flow/issues/3866

**Comment by oliver-sanders** [comment]
Note: we could potentially skip cyclic graph detection based on an arbitrary limit to the number of tasks or dependencies.

**Comment by MetRonnie** [comment]
Something I'm a bit puzzled by: why does the `_check_circular()` method use `[visualization]initial cycle point`? Why `[visualization]`?

This also ties into making that section obsolete as part of #3696

**Comment by oliver-sanders** [comment]
The visualisation ICP/FCP (Cylc7) define the window that the `cylc graph` visualisation tool uses (this is a static visualisation tool used to assist with workflow design). So rather than displaying the entire workflow (note the ICP/FCM might not be hardcoded in the workflow anyway) the visualisation settings can define a bit of the workflow that you want to look at.

I guess that graph validation just piggy-backed on this when provided so it ran over a sensible sized chunk of the graph?

Here's the PR that introduced the current system, though the visualisation settings were in use long before: https://github.com/cylc/cylc-flow/pull/2332.

**Comment by TomekTrzeciak** [comment]
How slow is too slow? We do some cycle detection with NetworkX on our suite and even on fairly large graphs this doesn't seem to be a problem. Eg. on a graph with 832 nodes it takes ~1 sec. and for 223987 nodes ~31 secs.

**Comment by TomekTrzeciak** [comment]
What happens if I run a suite with more than 100 tasks and circular dependencies? Does it just stall?

**Comment by MetRonnie** [comment]
Currently on master, with the following workflow:
```
[scheduling]
    cycling mode = integer
    [[graph]]
        R1 = a => b => c => d => a
```
it doesn't run anything:
```
INFO - Run: (re)start=0 log=1
INFO - Cylc version: 8.0a3.dev
INFO - Run mode: live
INFO - Initial point: 1
INFO - Final point: None
INFO - Suite shutting down - AUTOMATIC
INFO - DONE
```

**Comment by oliver-sanders** [comment]
(same situation as at present, cyclic graph detection is opt-in, currently via --strict)

**Comment by MetRonnie** [comment]
There isn't a `--strict` option for `cylc run` though?

**Comment by MetRonnie** [comment]
After discussing today, this behaviour of `cylc run` will remain unchanged
