### ISSUE TITLE
datastore ignores orphaned tasks

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4047]
If an active task gets orphaned by a reload (i.e. removed from the graph) it disappears from the datastore even though the scheduler allows it to continue running until finished.  It should stay visible as n=0 until done.

(Not a super high priority)

(current master branch)

**Comment by dwsutherland** [comment]
Must be because it no longer has a definition ... not sure what to do really, apart from allowing proxies without definition.

**Comment by hjoliver** [comment]
Could we just extract the tdef from the orphaned task proxy object?

**Comment by hjoliver** [comment]
> apart from allowing proxies without definition.

What are the consequences of that, for the datastore?

**Comment by dwsutherland** [comment]
> Could we just extract the tdef from the orphaned task proxy object?

We could do that, however, we'd need to construct the data-store definition from that also (and then there's families)

> > apart from allowing proxies without definition.
> 
> What are the consequences of that, for the datastore?

Orphaned task proxy could mean relationships are missing.. The task proxy's family hierarchy and task definition may not be there..

So it might work if we:
- stick the orphaned ones under root (instead of the potential missing family structure)
- generate the task definition as best as we can (things like family relation ship would have to default to root too)

The deletion of the task proxy should strip the relationship ID from root and task def .. However, we'd need to clean out it's task def too (perhaps add an orphaned tag as a field of both)..

**Comment by hjoliver** [comment]
> stick the orphaned ones under root (instead of the potential missing family structure)

That's fine, we do exactly the same in the scheduler (see `config.adopt_orphans()`)

> generate the task definition as best as we can (things like family relationship would have to default to root too)

Just take what's in the orphaned task proxy's `.tdef`. 

IMO we need to keep orphaned tasks visible in the UI while they're still alive, otherwise users might not be aware they'll still using up resources.
