### ISSUE TITLE
platforms: localhost platform patterns

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4117]
Platforms can be defined with patterns e.g:

```
[platforms]
    [[one,two]]
    [[one|two]]
    [[(one|two)]]
    [[*]]
```

Unfortunately if `localhost` is defined as a pattern it gets ignored due to a `localhost` default defined in the cfgsepc

```
[platforms]
    [[one,localhost]]  # one will get this config, localhost will not
```

Here's the default which is causing the issue:

https://github.com/cylc/cylc-flow/blob/07c7f5c9c785f097066ffdf8d4d5630b5914d734/cylc/flow/cfgspec/globalcfg.py#L607-L608

**Pull requests welcome!**

**Comment by dpmatthews** [comment]
> Unfortunately if localhost is defined as a pattern it gets ignored due to a localhost default defined in the cfgsepc

Actually I'm not sure that's true. You get an extra `[localhost]` section added into the config (and reported by `cylc get-global-config`) but it gets ignored by the platforms logic which find the matching pattern first. So, I don't think it actually causes a problems but it's still worth fixing to avoid confusion.

**Comment by wxtim** [comment]
> Remove the localhost default from the cfgspec (it doesn't give us anything at the moment anyhoo)
	Add logic to explicitly set it if not defined in def load #765 (see _set_default_editors for example of derived config)

Useful note copied from another forum.

**Comment by wxtim** [comment]
> Unfortunately if localhost is defined as a pattern it gets ignored due to a localhost default defined in the cfgsepc

This is definitely not true.
The fallback localhost platform created by the globalconfig is always first in the list of platforms. 
The search works backwards through the list (so that user configs override).
Fallback localhost should always be over-ridden by any other setting of localhost, but wasn't being, because I hadn't got the right treatment of multiple platform names in one platform entry.

I don't think that we need to remove the fallback localhost platform: It's quite normal to have over-ridden platforms near the top of the list...
