### ISSUE TITLE
Cylc 8 Cylc Review-Timings

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#4351]
`cylc review-timings` (CRT) needs to be checked for problems when working with Cylc 8.

We should consider:
- Does Cylc8 cylc CRT on a wide variety of workflows?
- Should you be able to use Cylc8 CRT on Cylc 7 workflows or should it fail loudly?
- Adding unit tests for CRT
- Check that CRT is actually documented.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
> Does Cylc8 cylc CRT on a wide variety of workflows?

Yes, it's independent of workflow structure (works on job timing info).

> Should you be able to use Cylc8 CRT on Cylc 7 workflows or should it fail loudly?

No, we shouldn't expect it to work on Cylc 7 workflows, although it may well still function.

> Adding unit tests for CRT
> Check that CRT is actually documented.

The plan is to add analytics functionality into the GUI - https://github.com/cylc/cylc-ui/issues/262.

* The GUI (especially with potential Jupyter Lab integration) would offer a really nice interface for this, e.g. interactive Pandas dataframes or filterable pivot-tables, etc.
* The GUI (due to the power of GraphQL and the UIS) would have the potential to query data from multiple workflows simultaneously making this more attractive.
* We would like to encourage users who are making use of the database to move in the direction of GraphQL, partly because it's more powerful and better documented, partly because it's a more stable interface, partly because it's independent of database structure which we would like to change #3872.
* There are some other ideas for this data including the gantt view https://github.com/cylc/cylc-ui/issues/181

Consequently the pressure on this command may reduce in the near future so would stick this on the back-burner unless there is a lot of interest in this functionality as a CLI util in the user-base.
