### ISSUE TITLE
Replace cylc.flow.timer doctests with unit tests

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4413]
#4343 broke pytest for Python 3.9

https://github.com/cylc/cylc-flow/blob/3cabcf7e93201b17cdefa0c093b7d1a5a91e2093/cylc/flow/timer.py#L28-L34

The `LOG.warning` is not properly patched so the lambda remains after this doctest has run.

I think we should replace this doctest with unit tests and use `caplog` to test the logging.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
> #4343 broke pytest for Python 3.9

It works fine with 3.9 in my environment. 

![shot](https://user-images.githubusercontent.com/2362137/133513789-f5b2ce84-0a59-483a-be8b-be3bc545df84.png)

But OK, I'll convert to proper unit tests...

**Comment by hjoliver** [comment]
OK, because I'm strapped for time, and this is only a small test, I pushed a quick hot fix to master for the existing doctest (patch, then unpatch `LOG.warning`): https://github.com/cylc/cylc-flow/commit/64d7f385b04a01697b5e542b072863286911ae6b

Which means we can de-prioritize this issue and un-bug it. And maybe close it - or is my monkeybatch bodge considered too ugly and/or too much for a doc test?  (Obviously it would not be a difficult translation to unit tests ... but there's a lot to do right now).
