### ISSUE TITLE
Refactor workflow_files

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4414]
`cylc.flow.workflow_files` has ballooned in size; some parts could do with splitting off into their own modules, e.g. clean, install, etc.

Also, some parts of `cylc.flow.pathutil` are perhaps better suited to `workflow_files`.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
Related to https://github.com/cylc/cylc-flow/issues/3345

**Comment by hjoliver** [comment]
:+1: (I did some significant refactoring of `workflow_files` during optional outputs development because I needed to plug into `suite.rc` detection for back-compat reasons and the associated code was getting pretty convoluted - but I backed out of those changes after a big rebase to concentrate on the main topic of my PR branch).
