### ISSUE TITLE
Tutorial workflow: messed up wind plot 

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4660]
~/cylc-run/cylc-forecasting-workflow/run1/work/20210723T0300Z/consolidate_observations/wind.png
![wind](https://user-images.githubusercontent.com/61982285/126769095-4cbc27e1-cd36-48bf-bc0c-dcfd8a462494.png)

**Comment by wxtim** [comment]
> Do you still get this error? I don't.

And now.. I do

I'm pretty sure that one of the plots has got it's lat-long co-ords flipped, so that one of the plots is from 
Lat -12 to +1 and Longitude 48 - 61 (A chunk of the Indian Ocean vaguely near the Seychelles), and the other from Lat 48-61 and Long -12 to +1 (A chunk of the North Atlantic with a few insignificant islands)...

As a result the overall plot is plotting a large chunk of Europe and the Western Asia.
