### ISSUE TITLE
mutations: add workflow states metadata

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4726]
Find a way to add metadata to mutations covering the workflow states for which the mutation is valid.

E.G. the stop mutation is only valid when the workflow state is in `{running, paused}` and the resume mutation is only valid when the workflow state is in `{paused}`.

The UIs can then grey-out mutations as appropriate: https://github.com/cylc/cylc-ui/issues/868

The easiest way to add this metadata is probably in the mutation help text where it would also serve as documentation.

**Pull requests welcome!**

**Comment by datamel** [comment]
I looked into this on Friday. I could not see a way of adding a bespoke meta field using the inbuilt graphql meta class and so have gone ahead with solving this with a regex pattern match of the form: e.g `Valid for: ['stopped', 'paused'] workflows.` in the description field. This is a bit of a frustration, since new mutations will need this adding, however devs would have needed to remember to add the meta field had this been possible. Also, this acts as a type of documentation for the users which may be useful for them.
