### ISSUE TITLE
Add "preparing" to list of filterable states.

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#4782]
### Describe exactly what you would like to see in an upcoming release

In the "Tasks" view use the detection of Cylc version to change the list of filterable task state tick boxes.

If the workflow is Cylc 8:

- The user should be able to filter by `state="preparing"`
- The user should **not** be able to filter by states not in [this list](https://cylc.github.io/cylc-doc/latest/html/user-guide/running-workflows/task-job-states.html?highlight=task%20states)

Additionally at Cylc 7 #2938 waiting was unticked by default. We should examine #2938, to see if we can enable the tickbox by default for Cylc 8 flows.

### Additional context

![Screen Shot 2022-03-29 at 11 12 34](https://user-images.githubusercontent.com/26465611/160589167-b663019f-9fa6-4056-9c14-d49079e31bac.png)

The code change should be near the assignment of `task_statuses` at line 320 of `review.py`. You may also wish to add a clone of `TASK_STATUSES_ORDERED` in `task_state` to hold Cylc 8 task states.

### Testing

This is a legacy back compatibility piece of functionality, and should be tested manually.

**Pull requests welcome!**

**Comment by dpmatthews** [comment]
> Additionally at Cylc 7 https://github.com/cylc/cylc-flow/pull/2938 waiting was unticked by default. We should examine https://github.com/cylc/cylc-flow/pull/2938, to see if we can enable the tickbox by default for Cylc 8 flows.

With "waiting" enabled you end up with lots of tasks listed with no associated jobs which is pointless.
If we discard any waiting tasks with no jobs I think it should be fine to enable this by default.

**Comment by hjoliver** [comment]
Presumably `cylc review` can only show `waiting` tasks that exist in the DB, which corresponds to waiting tasks in the scheduler task pool - not the scheduler datastore (and therefore, unaffected by n-window size).

Cylc 7 had loads of those, due to pre-spawning of waiting tasks.

Cylc 8 only has "active waiting" tasks: i.e., with partially satisfied task prerequisites, or fully satisfied but waiting on a clock trigger or other xtrigger.

So I would think it's OK not to discard those or filter them out by default in `cylc review`.

**Comment by wxtim** [comment]
I think #4897  actually closes this issue.
