### ISSUE TITLE
Review `iso8601.py` code comments (and code?)

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4805]
There are several cryptic comments such as

https://github.com/cylc/cylc-flow/blob/5a194331aeda920503d701dc46009d1816682dd9/cylc/flow/cycling/iso8601.py#L669-L677

https://github.com/cylc/cylc-flow/blob/5a194331aeda920503d701dc46009d1816682dd9/cylc/flow/cycling/iso8601.py#L771-L782

In the latter, unfortunately the linked PR https://github.com/metomi/isodatetime/pull/101 is not very illuminating to me! (And the discussion there appears as if it might be suffering from confusion over the "addition of truncated TimePoint" bug https://github.com/metomi/isodatetime/issues/80, to boot)

Also, is it just me or are the regexes in the code alarmingly simple? We should see if we can find faults in them.

**Comment by hjoliver** [comment]
Maybe the authors of those comments will remember. The first were by @lhuggett ; then second by @oliver-sanders .

**Comment by lhuggett** [comment]
So I think what the first one was about was that if you include the year (and/or month) from the real "now" when you're not looking at a day as well, you end up with a false earliness, so you move it (them) forward one to make sure the next/previous works correctly. I do recall that I only found it by trial and error.

For the second one, I'm afraid I don't remember what the issue was about the potential breakage from the reversing of tickover order, only that it was something that we thought could be a problem but hadn't actually been demonstrated as one at that point.

**Comment by MetRonnie** [comment]
Thanks for the response, looks like this comes down to a possible bug in isodatetime:
```python-console
>>> now = TimePointParser().parse("2010-08-08T15:40Z")
>>> point = TimePointParser(allow_truncated=True).parse("-10")
>>> now + point
<metomi.isodatetime.data.TimePoint: 2010-08-08T15:40:00Z>
>>> now == now + point
True
```
I think `now + point` ought to equal `2110-08-08T15:40:00Z`

**Comment by MetRonnie** [comment]
For the second, I think I have figured it out: https://github.com/metomi/isodatetime/issues/212
