### ISSUE TITLE
`cylc reinstall` fails inside symlink run dir

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4928]
**Steps to reproduce the bug**

Have `[install][symlink dirs][localhost]run` set to some location
```console
$ cylc install myflow
INSTALLED myflow/run1 from ~/cylc-src/myflow
$ cd myflow/run1
$ cylc reinstall
WorkflowFilesError: The current working directory is not a workflow run directory
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
I think this is ok, `$PWD` was really for `cylc install` installing relative to the source directory, `cylc reinstall` reinstalling relative to the run directory seems erroneous to me, certainly confusing (since it wouldn't work if you ran it from the source directory as with install?).

Simplest option is to drop `$PWD` support from `reinstall`.

The less simple option (to preserve this functionality) would be to look for a `flow.cylc` or `suite.rc` file, if it is found, search the directory path for a `cylc-run` dir and extract the relative path from that dir. This should be the workflow ID.
