### ISSUE TITLE
CYLC_WORKFLOW_NAME: use the "flat" name

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4977]
Many Cylc 7 workflows have been assuming a flat workflow ID (despite hierarchical registration going back to Cylc 6). With Cylc 8 hierarchical workflow IDs are now the default because run numbers are turned on by default.

To assist with the transition we added the `CYLC_WORKFLOW_NAME` environment variable (not to be mistaken with `CYLC_WORKFLOW_ID`) which is the ID with the run name/number stripped off.

Since https://github.com/cylc/cylc-flow/issues/4643 we have introduced another mechanism by which you can get hierarchical IDs "by default" in that we now transfer the directory structure from the src to the run dir.

Given its name you might expect the `CYLC_WORKFLOW_NAME` environment variable to reflect the "base name" of the workflow and not reflect its "path" either src or run. E.G for an ID of `a/b/run1` the "name" part might be considered to be `b` rather than `a/b`, especially since the src dir structure is likely to reflect project organisation.

**Question:**
* [ ] Should `CYLC_WORKFLOW_NAME` be "flat" or "hierarchical"?

**Pull requests welcome!**

**Comment by TomekTrzeciak** [comment]
My vote would be to keep it hierarchical. Not quite sure what would be the use for basename alone, plus it's easier to split on `/` to get the basename than to reconstruct the hierarchical name from basename &  `CYLC_WORKFLOW_ID`.

**Comment by oliver-sanders** [comment]
> Not quite sure what would be the use for basename alone

MASS!

**Comment by hjoliver** [comment]
The other problem with `CYLC_WORKFLOW_NAME` is it could legitimately be assumed to be the direct Cylc 8 translation of `CYLC_SUITE_NAME`, which was the full "ID" and as such would presumably include the run name (albeit, created manually if used at all with Cylc 7).

Since 8.0 is (not quite) out yet, I wonder if we could reformulate these variable names to make it clearer?  Off the top of my head:

- `CYLC_WORKFLOW_ID` - the works, obviously
- `CYLC_WORKFLOW_NAME` - the full hierarchy with just the run-name stripped off
- `CYLC_WORKFLOW_BASENAME` - just the basename, by analogy with shell commands (presumably sans run-name, though)
- `CYLC_WORKFLOW_DIRNAME` - the relative path under ~cylc-run down, to the basename (by analogy with shell commands)

**Comment by oliver-sanders** [comment]
We've been going through a similar thought process. Personally I can't think of any especially legit uses for the hierarchical ID minus the run name (possibly until we support sub-workflows properly?). The most pressing issue for us ATM is providing easy access to the "basename" minus the run name (e.g. for `a/b/c/run1` we need `c`) to help our users to migrate widespread engrained working practices which have assumed flat installation.

**Comment by hjoliver** [comment]
@oliver-sanders - this will be an easy fix, but we need to decide and agree on a solution. Can you propose one? 

>  I can't think of any especially legit uses for the hierarchical ID minus the run name 

Even if that's the case, it might be worth providing the full set (as per my suggestion) because as a group they make sense and could be documented like this:

> An installed workflow has a *name*, which is path relative to cylc-run: `a/b/c/cheese`.
> A named workflow may have multiple *runs*, in sub-directories: `a/b/c/cheese/runN`
> 
> Cylc provide the following related variables to task environments:
> - `CYLC_WORKFLOW_NAME` -  the name of the workflow: `a/b/c/cheese`
> - `CYLC_WORKFLOW_ID`  - the full ID of a specific run: `a/b/c/cheese/runN`
> - CYLC_WORKFLOW_BASENAME` - the basename of the named workflow: `cheese`
> - CYLC_WORKFLOW_DIRNAME` - the dirname of the named workflow (relative to cylc-run): `a/b/c`
> 
> Note that the "name" of the workflow includes the directory hierarchy.

**Comment by dpmatthews** [comment]
> (Could we provide back-compat SUITE variables to support the Rosie use case above?)

We already provide `CYLC_SUITE_NAME` (same as `CYLC_WORKFLOW_ID`). We can't change the meaning of this because that would break other use cases.

`CYLC_WORKFLOW_BASENAME` doesn't make it clear what it is the basename of - the workflow name or the workflow id?
How about:
* `CYLC_WORKFLOW_NAME_BASE` - the basename of the workflow name
* Remove `CYLC_WORKFLOW_NAME` - we can always add it again later if there is demand

**Comment by hjoliver** [comment]
> CYLC_WORKFLOW_BASENAME doesn't make it clear what it is the basename of - the workflow name or the workflow id?

That's why my proposed documentation above emphasizes that "the workflow" does not include the run-name - because a workflow can have multiple runs (each with a unique ID however).

However, I quite like your suggestion.

And `CYLC_WORKFLOW_NAME_DIR` as well, to go with ...NAME_BASE?

**Comment by dpmatthews** [comment]
> And CYLC_WORKFLOW_NAME_DIR as well, to go with ...NAME_BASE?

I don't think we should add anything more unless there is user demand.

**Comment by oliver-sanders** [comment]
There shouldn't be any legit uses for this but I'm sure there are plenty of dodgy ones so I'd rather punt this one into the future until we have a use case. Note this may end up being related to sub-workflows (when implemented in a nicer way).
