### ISSUE TITLE
queues: configure a default "default queue" limit

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5010]
The "default queue" has an infinite limit which probably isn't a sensible feature for Cylc to have.

It would be a reasonable safety feature to put an upper limit on this by default (note it can be easily configured on a per-site and per-workflow basis). The default could be a relatively high value, just not infinite:

```ini
[scheduling]
    [[queues]]
        [[[default]]]
            limit = 500
```

Context: Large numbers of simultaneous submissions can:

* Overwhelm job runners.
* Overwhelm the main loop making workflows unresponsive.
* Result in very large DB writes.

**Pull requests welcome!**

**Comment by hjoliver** [comment]
:+1: good idea

**Comment by dpmatthews** [comment]
If this is a safety feature I suggest we go for something lower.
It's too easy to set up a workflow that can overwhelm the scheduler host with local tasks.
How about a default limit of 100?
That's high enough that most workflows won't notice it but low enough to give hosts a chance to survive.
If your workflow needs to run more than 100 tasks at once it probably makes sense to force you to configure an appropriate limit (in which case perhaps this should be a fixed default rather than site configurable?).

**Comment by oliver-sanders** [comment]
The real issue for CPU/hosts is the number of simultaneous submissions rather than the number of active (which includes running) tasks. Worth noting that simultaneous submissions could be limited separately if desired.

E.G. this diff should be enough to restrict the number of preparing jobs (may also require a `list.sort` somewhere):

```diff
-             pre_prep_tasks = self.pool.release_queued_tasks()
+             pre_prep_tasks = self.pool.release_queued_tasks()[:simultaneous_prep_limit]
              if not pre_prep_tasks:
                  # No tasks to submit.
                  return
```

https://github.com/cylc/cylc-flow/blob/5658163cb97bac3a653d7b035c1713abf17a2377/cylc/flow/scheduler.py#L1259-L1262

**Comment by oliver-sanders** [comment]
I'm happy with a default limit of 100. Seems a reasonable number and easy to override.

**Comment by oliver-sanders** [comment]
Converted into a PR, removing the question label (we can discuss it there)
