### ISSUE TITLE
cat-log: use --follow=name

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5341]
There's a potential issue where tail processes started by `cylc cat-log` can cause network file systems to keep files open for reading even after they have been deleted. These tempfiles can cause `cylc clean` to fail because the filesystem won't let it delete the file.

The `tail` command has a `--follow` option which can be set to `name` (as opposed to descriptor) which may solve this problem.

If it works this is a more elegant solution to [#417](https://github.com/cylc/cylc-uiserver/issues/417) which would only work at the UIS layer.

**Pull requests welcome!**

**Comment by datamel** [comment]
I have tried this out and it does not fix the `cylc clean` error in the gui for me.

There are two scenarios that cause `cylc clean` to error, both occur when the log view is up and the subscription is active:
- the workflow is running and the log is still writing, this results in a `ServiceFileError`
- the log is closed (e.g. stopped workflow), this results in a `FileRemovalError`

Note, we can change the tail command in the  [global config](https://github.com/cylc/cylc-flow/blob/9e042645c92b871a07e07c3a90a73bb2ff5c99e8/cylc/flow/cfgspec/globalcfg.py#L1428) which may have been helpful as an immediate fix.

I think the way forward with this problem is to close the subscription on clean. This could be done from the ui or ui-server. I'll have a look into which one works best.

**Comment by datamel** [comment]
As an aside, I think it sensible to have the clean button in the ui disabled if the workflow is still running.

**Comment by oliver-sanders** [comment]
> As an aside, I think it sensible to have the clean button in the ui disabled if the workflow is still running.

https://github.com/cylc/cylc-flow/issues/4726

**Comment by oliver-sanders** [comment]
Closed by #5359
