### ISSUE TITLE
expiry: broken interaction with runahead limit

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5447]
There is a bug in the interaction between runahead limit and task expiry.

In the following example, Cylc spawns the task out to the runahead limit, these tasks then clock-expire. The task pool is now empty so the workflow shuts down, job done, despite there still being un-expired tasks left to run before the FCP.

```
[scheduling]                                         
    initial cycle point = previous(T-00) - PT5H    
    final cycle point = +PT10H    
    runahead limit = P3                                                                                                            
    [[special tasks]]                                
        clock-expire = task1(PT0H)                   
    [[dependencies]]                                 
        [[[R//PT1H]]]                                
            graph = "@wall_clock => task1"           
                                                     
[runtime]                                            
    [[task1]]
```

**Comment by hjoliver** [comment]
This is fixed by #5412 - although we had better check again once that PR is finished.

Running your example on that branch, the workflow stalls with incomplete tasks and a runahead-limited task in the pool, rather than shutting down. . If I remove a few expired tasks, I eventually get a task waiting on a new clock trigger.

(Note stall on expired tasks - i.e. considering them as incomplete - is still under discussion).
