### ISSUE TITLE
Triggering `1/x` in a new flow causes `x` to spawn in future cycles as well

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#5555]
### Description / Reproducible Example

```
[scheduler]
    allow implicit tasks = True
[scheduling]
    cycling mode = integer
    final cycle point = 3
    [[graph]]
        P1 = x
```

```console
$ cylc play workflow
# After it has shut down:
$ cylc play workflow --pause
$ cylc trigger workflow//1/x --flow=new
```

And `x` spawns at every cycle point.

### Expected Behaviour

`x` only spawns at cycle 1 because there are no inter-cycle dependencies?

**Comment by hjoliver** [comment]
This is the expected (and correct) behaviour.

If you trigger a new flow, it should behave just like the original flow - which it does. 

The reason is that `x` has no parents at all, so it can't be spawned on demand by parent tasks in its flow. And, having no prerequisites, all future instances of `x` are technically ready to run at once.  So, the scheduler spawns all of them at once (out to the final cycle point or the runahead limit, whichever comes first). That goes for the original flow, and for the new flow.

If you only want `1/x` to run, don't use `--flow=new`.

I'll close this issue - reopen if you feel there's something to argue with here!

(We should explicitly mention this in the docs though; I'm sure many users will be unsure what to expect here).

**Comment by MetRonnie** [comment]
I see. Where it got confusing was
```
P1 = """
    (x & a) => b
    b[-P1] => a
"""

After the workflow had run once, triggering `1/b` in flow 2 lead to a stall by the time `2/a` finished, then triggering `2/x` in flow 2 fixed this but somewhat unexpectedly spawned `3/x` at the same time. But when you wrap your head around it, it makes sense.
