### ISSUE TITLE
event emails should include associated task messages

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5566]
REF: https://cylc.discourse.group/t/sending-custom-emails-from-cylc-workflow/665

```ini
[scheduling]
   [[graph]]
      R1 = "foo"
[runtime]
   [[foo]]
       script = """
          ON_THE_FLY=$(date)
          cylc message WARNING:"My birthday is ${ON_THE_FLY}."
       """
       [[[events]]]
           mail events = warning
```

Running this results in an email to the user, for the warning event, but it does not include the associated task message.

The only way to get custom content into the email seems to be `[scheduler][mail]footer` which allows templating of workflow-level variables (so not task-level `%(message)s` etc.

Fixing this is probably complicated by event-batching for emails.

**Comment by oliver-sanders** [comment]
The message is not present in the `id_key` which means this missing context would need to be added. This is a right pain due to the number of functions which use this key with tuple unpacking, so would be broken by any change to its format. 

I think this `id_key` logic should get straightened out either way, suggest using a named tuple to carry the context info and passing the `Tokens` object to avoid repeated ID formatting, then adding the message into the named tuple. This should be an 8.3.0 change as the risk of breakages is quite high.

**Comment by oliver-sanders** [comment]
Assigning myself as I've been having a poke around the id_key problem.
