### ISSUE TITLE
Spawning parentless clock-xtriggered task

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#5572]
Reported by @hjoliver on Element:

Consider a cycling graph with a parentless clock-xtriggered task foo at the top of each cycle. Currently (perhaps pending a future capability for clock triggers to spawn dependent tasks on demand):

* the clock-xtrigger requires a waiting foo in the active pool, to wait on it
* successive instances of foo get auto-spawned out to the runahead limit (there are no parent tasks to do It)

At normal start-up, the first instance of foo gets spawned by the scheduler, then (having no parents to do so) it spawns future instances of itself.

However, when triggering a new flow, or when starting up with `--start-tasks`, at some other point in the graph, we likely need to arrange for the "next" instance of foo to be spawned as waiting on the clock-xtrigger. At the moment this can't be done (since `cylc spawn` was removed):
* triggering a previous instance of foo will spawn the correct "next" one, but it will cause unwanted action downstream of the previous instance
* triggering the "next" instance will cause it to run before it's clock-xtrigger is satisfied
* setting outputs or prerequisites won't help

**Comment by dpmatthews** [comment]
We already have the case that trigger actually just queues a task and you need a second trigger to make it run immediately.
We could extent this to:
* Triggering a task that doesn't have all it's pre-requisites met marks it as ready to run subject to any clock trigger (in the absence of any clock trigger it will be queued).
* Triggering a task that is purely waiting on a clock trigger queues it.
* Triggering a task which is queued submits it regardless of any queue limits.

I quite like this because it avoids the need to remember to use a different command when dealing with a clock triggered task.
In the vast majority of cases (tasks that don't have clock triggers or have clock triggers which have already passed) it would be no different to now.

**Comment by dpmatthews** [comment]
See also https://github.com/cylc/cylc-doc/issues/476

**Comment by hjoliver** [comment]
Hmmm, on reflection, there is a problem for my use case above,

Going by your rules, a clock-triggered parent-less task should be queued to run if manually triggered, because it has no prerequisites, even if it is an abstract task in the future graph (i.e. not in `n=0` yet).

The problem is I start the flow part way through the graph in a particular cycle, so none of these parent-less clock-triggered tasks get spawned at all. I want to spawn them manually into `n=0` as waiting on their clock-triggers, in order to set up the next cycle to run when the time comes.

I guess the first rules would have to be:
- Triggering an abstract task spawns it into `n=0` with prerequisites (but not clock-triggers) satisfied
- Triggering a waiting `n=0` task satisfies any prerequisites, and queues it if not waiting on a clock-trigger
- Triggering a task waiting only on a clock trigger, queues it
- ... (same from here)

As a consequence, to make a parent-less clock-triggered task queue immediately you will have to be trigger it twice if abstract but only once if in `n=0`.

On the other hand, they do already need to understand the difference between waiting `n=0` tasks and "waiting" abstract future tasks for a couple of other reasons (e.g. `n=0` already have flow numbers assigned, and can cause flow merging).

What do you think?

**Comment by hjoliver** [comment]
> As a consequence, to make a parent-less clock-triggered task queue immediately you will have to trigger it twice if abstract but only once if in n=0

Actually, that's similar to triggering unqueued vs queued tasks too.  So maybe that's OK.

**Comment by dpmatthews** [comment]
Yes, sorry. What you describe is what I had in mind. It's just difficult to know the best way to describe this without referring to spawning and n=0 and without inventing new terminology (e.g "abstract task"!). The current help for `cylc trigger` says "Force tasks to run despite unsatisfied prerequisites" which already doesn't make a lot of sense when applied to new flows or to parentless tasks so we could do with improving this.

**Comment by hjoliver** [comment]
> and without inventing new terminology (e.g "abstract task"!).

I have used that terminology on and for ages, to distinguish a "concrete" task (which is represented by a task proxy object in the scheduler) from one that only exists in an abstract sense - somewhere ahead in the potentially infinite graph.

But yes, it difficult to write clearly about this stuff.  For users, I'm hoping `n=0` or `active task window` will do.

**Comment by hjoliver** [comment]
@oliver-sanders - 

Trigger does already have this trigger behaviour - for queued tasks.

Also, although I didn't actually say it above, I have been assuming that:
- we'll need "run now despite all constraints" capability, as well as this layered approach
- the specific user interface is still subject to revision under the terms of the `cylc set` discussion (and it may indeed end up under `cylc set` rather than `cylc trigger`).

However, in the interim (`cylc set` has been a long time coming!), I've implemented it in the only current suitable command (which is `cylc trigger`) because I need this functionality pretty quickly for a certain DR project (which involves starting up part way through a cycle point).

> This isn't just about clock-triggers but xtriggers in general.

It should be about xtriggers in general. We need to be able to "trigger" xtriggered tasks, in general, not to run immediately but to start checking on their external condition.

**Comment by hjoliver** [comment]
> It's just difficult to know the best way to describe this without referring to spawning and n=0 and without inventing new terminology (e.g "abstract task"!)

That's not really an argument against this or any other functionality unless if there another way to do it that avoids any need to understand these concepts (whatever names we give them). That we haven't settled on the terminology doesn't necessarily imply that is possible to avoid the concepts.

Unlike in Cylc 7, the Cylc 8 scheduler task pool makes good intuitive sense as the "n=0 active window" on the graph (which only contains "active tasks", with some provisos on exactly what "active" means).  "Spawning" now just refers to how a tasks gets into that window. Users have to understand what the n=0 window is, in order to understand what they are seeing in the UIs.

**Comment by wxtim** [comment]
@dpmatthews  - Can I check my interpretation of this:

```
srcdir=${HOME}/cylc-src/delme
mkdir -p ${srcdir}
cd ${srcdir}

cat > flow.cylc <<__ICI__
[scheduler]
    allow implicit tasks = True
    cycle point format = %Y

[scheduling]
    runahead limit = P1Y

    initial cycle point = 1000
    hold after cycle point = 1005
    [[xtriggers]]
        xt = xrandom(24, 0, 'some label'):PT1S
    [[graph]]
        P1Y = @xt => foo => bar
__ICI__

cylc vip . 

# Watch until flow has decent head start/hits the hold after then ctrl+c
cylc log -m t delme

cylc trigger delme//1000/bar --flow=new --meta='should-this-spawn-1000/bar'

cylc log -m t delme
```

Would we expect the trigger command to lead to the spawning on 1001/foo &c...?
