### ISSUE TITLE
dummy mode: subtract err-script from jobs

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5820]
In dummy mode, we remove any configured script items, except err-script for some reason.

See https://github.com/cylc/cylc-flow/pull/5721#discussion_r1391143979

**Comment by oliver-sanders** [comment]
@wxtim you might want to see if you can cross this off post skip-mode work, or have already resolved it as part of recent sim-mode work.

**Comment by wxtim** [comment]
**This makes sense because:**

* It's so under-utilized that we can probably do what we like.
* Any use case was probably from when dummy meant dummy-remote, not dummy-local.

**But...**

It makes sense to me that the user of dummy mode might want to keep the effect of the dummy script, especially if the error script is altering the workflow. If they were wanting to test a `cylc reset` or a `cylc message` or the state of the workflow.

Happy to remove it, but wanted to check that you've considered the reasons.

**Comment by oliver-sanders** [comment]
Dummy mode is supposed to run a dummy job commenting out all script. Given that dummy jobs should not fail (because they don't run anything), the inclusion of `err-script` should be symptomless (i.e. you can't use it to alter the workflow because it should never be called). The omission of `err-script` was an accident, likely because `err-script` was the most recently added of the bunch. Note that `post-script` (which is omitted) is essentially the "success" opposite of `err-script`.

**Comment by wxtim** [comment]
I will do this. 

> dummy jobs should not fail

Dummy jobs will currently fail if you set `[simulation]fail cycle points = all`.

**Comment by oliver-sanders** [comment]
> Dummy jobs will currently fail if you set [simulation]fail cycle points = all.

:vomiting_face: 

Hmm, dummy mode may require a rethink, or a deletion (see #5961).

**Comment by wxtim** [comment]
Also missing `exit-script` too.
