### ISSUE TITLE
Allow trigger-now in a paused workflow?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5963]
There is a valid use case (especially since the demise of the old `cylc submit` command for running individual tasks sans scheduler) early on in workflow development and debugging, for starting a workflow paused and then manually triggering individual tasks to run.

Currently "paused" means "don't run anything", so if you trigger a task in a paused workflow, the task won't run until the workflow gets un-paused.

I think we probably intended `cylc hold` for this sort of thing, but that doesn't do it without additional seemingly unnecessary effort: holding an already-active task (even via a "hold all" pattern) does not prevent downstream future tasks from running unless every one of those has also been specifically held.

So ... is there any good reason not to allow manual triggering (in the "run right now" sense) of tasks in a paused workflow?

See cylc/cylc-ui#1651

**Comment by ColemanTom** [comment]
I would personally like this (which is probably obvious based on the previous Issues I've raised).

**Comment by dwsutherland** [comment]
So would I, even to be able to release/resume a specific branch while the rest stays paused/held

**Comment by oliver-sanders** [comment]
Task hold and workflow pause are orthogonal features, there are advantages to being able to slam the brakes on a workflow, manual triggers and all. There are also interventions beyond trigger that can cause tasks to submit (e.g. set).

Holding all tasks in a workflow is a little clumsy at the moment due to future matching requirements (#5827), however, this is a priority issue to solve so should go away before too long. Holding all tasks via this interface achieves the desired result, IMO this is a better solution to changing the meaning of pause to satisfy this use case.

What remains (after #5827) is to improve access to task hold to make it easier to reach and more intuitive to use, ideas:
* Reinstate the `cylc run --hold` argument to start a workflow with all tasks held.
* Improve access to the Hold/Release commands in the GUI menu.
* Consider changing the default task list in the GraphQL mutations for Hold/Release from `null` to `*/*`. This would mean that if you clicked the Hold command from the workflow menu, it would hold all tasks by default without the user having to type `*/*` into the box.

With this using hold/release would be as convenient as using play/pause.

**Comment by hjoliver** [comment]
> there are advantages to being able to slam the brakes on a workflow, manual triggers and all.

Not sure I buy this. What's the advantage of being able to slam the brakes on manual "trigger now" exactly? By definition that means run this task now, so I wouldn't do it in the first place if there was any reason I didn't actually want it to trigger.

There's nothing fundamentally wrong with `cylc pause` meaning "the scheduler will not *automatically* submit any tasks" but the user can still do it manually. 

It's conceptually (and implementation-ally) simpler than `cylc hold "*"` which requires understanding how the glob applies to active and future tasks. 

There's quite a bit of work to do to get hold/release working in the way users expect for this sort of thing (see above) but it would be trivial to get it working as proposed in this issue. If we did that, it wouldn't matter that a similar thing might be achievable both ways in the future. After all, there's a lot conceptual overlap between `cylc pause` and `cylc hold '*'`.

**Comment by hjoliver** [comment]
(Question label removed, as it was already on the associated PR)
