### ISSUE TITLE
Cylc 8 not properly matching hostnames given in global.cylc

### ISSUE THREAD

**Issue by retro486** [cylc/cylc-flow#6005]
This is an issue we're seeing on hosts that are part of a round-robin DNS or have multiple DNS entries.

Our hosts that are part of a round-robin DNS have the generic FQDN listed last in "hostname -A" output, and that seems to be how Python 3's socket.getfqdn() is resolving the current host name rather than returning the unique FQDN of the current host.

For example: instead of getting "apps24.localdomain" it's returning "apps.localdomain", and "hostname -A" output would be "apps24.localdomain apps.localdomain".

Instead, it should use something like the user mentions in [this SO answer](https://stackoverflow.com/questions/11580023/how-do-i-get-my-computers-fully-qualified-domain-name-in-python#comment38763823_11580042) which seems to result in more accurate results, getting the individual hosts' FQDN instead of the round-robin entry.

I've tested this and it seems to work and prevents us from having to use hardwired names which I think is causing other problems (#6004).

hostuserutil.py diff:
```
120,122c120
<                 #target = socket.getfqdn()
<                 target = socket.getaddrinfo(socket.gethostname(), 0,
<                     flags=socket.AI_CANONNAME)[0][3]
---
>                 target = socket.getfqdn()
```
The direct list index access feels icky but as a test it seems to resolve the issues I'm reporting here.

**Comment by oliver-sanders** [comment]
Finding the FQDN on HPC systems is often awkward due to complex DNS setup. Finding an approach that works for most cases has taken us some time. Cylc is using the `getfqdn` interface which is what Python recommends for this purpose, e.g. see this quote from the `socket.getaddrinfo` method docs:

> To find the fully qualified domain name, use the function [getfqdn()](https://docs.python.org/3/library/socket.html#socket.getfqdn). [gethostbyaddr()](https://docs.python.org/3/library/socket.html#socket.gethostbyaddr)
>
> -- https://docs.python.org/3/library/socket.html#socket.getaddrinfo


The behaviour of `getfqdn` *tends* to match `hostname -f`, however, the behaviour of this, and other, socket interfaces can vary according to OS and even Python build. I'm not sure that SO comment is correct about the inner workings of the `getfqdn` interface. The behaviour that you're seeing, may be specific to your Python build + DNS setup. On my platform the FQDN does not appear in `/etc/hosts` but `getfqdn` still returns the right result.

To understand why the same interface can give different results, take a look at the source of the interface that `getfqdn` calls:

https://github.com/python/cpython/blob/0704166f9a9c6028314d50b493670e7862c968b3/Modules/socketmodule.c#L5954

The large number of `#ifdef` statements in that code show how radically one build can differ in implementation from another.

So unfortunately, this is a Python build / OS / DNS issue rather than a Cylc bug.

To help work around these issues, I did once try to refactor the configuration to allow sites to configure the method that Cylc uses to return the FQDN to something that works with the local setup. This turned out to be a bit involved so I didn't follow through with it at the time, but this is still a possibility if needed.

If you haven't tried it already, you might want to look at Cylc's `address` based approach which is generally more robust to DNS configuration:

https://cylc.github.io/cylc-doc/stable/html/reference/config/global.html#global.cylc[scheduler][host%20self-identification]method

**Comment by oliver-sanders** [comment]
@retro486, have you managed to find a workaround for this?

**Comment by retro486** [comment]
I was able to get it working by hardwiring the workflow host IP address for self-identification, like you recommended, and then I used localhost for the hostnames (since we're not making use of more than one workflow host per platform) and that seems to have worked. When I tried using the FQDN Cylc was still trying to ssh to the local machine, but I had to move on so we accepted the localhost/IP solution.

I did have to make sure I was using the correct interface that would allow the compute nodes to communicate back to the workflow host ("duh" but it was something worth noting when you have 4-5 available interfaces on the workflow host).

You could probably close this since it's not a Cylc bug but rather a limitation in Python 3's sockets implementation, though there's probably no good answer short of "just tell the software where you want it".

**Comment by oliver-sanders** [comment]
Cylc's requirement of fully consistent DNS across the whole network has caused several problems, especially with HPC setups which can be a little unusual.

I think the best way forward will be to loosen our requirement where possible and make the underlying interface we use configurable so that sites can use what works for them. I've added a couple of comments to this issue:

https://github.com/cylc/cylc-flow/issues/3768
