### ISSUE TITLE
clock-expire: prevent active tasks from being clock-expired

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#6025]
From discussion on https://github.com/cylc/cylc-flow/pull/6020

Clock expiry can complete a task.

If the task is already active then it should not be completed in this way.

Note, I think we would expect a clock-expired task to be able to expire between retries.

**Comment by hjoliver** [comment]
Relatedly, we should probably not allow any final output (i.e., expired, submit-failed, failed, succeeded) to be manually set on an active task. 

Setting these outputs also changes the task state to a final state, which is inconsistent with having a submitted or running job. And we have previously decided that only `cylc kill` can kill jobs.

We could decide not to change the state of an active task via `cylc set`, so you could (e.g.) trigger a downstream success branch while the task is still running, but it seems more reasonable (and consistent with setting final outputs in non-active tasks) to disallow it. The user can always kill the job, then set the final output.

**Comment by hjoliver** [comment]
No it doesn't (at least not explicitly!)

By active, I meant literally active, i.e. "submitted" or "running", not just "present in the task pool".  

The proposal only explicitly states that we should be able to cancel a retry chain by setting a final output.

Typically that would happen after a job fails and is *waiting* for a retry. Setting a waiting task to failed is perfectly fine. Setting a running task to failed leaves an orphaned  job out in the world, which can be confusing or worse (if the user triggers the task again they will end up with duplicate jobs fighting it out on the filesystem).

So, if the task is *active*, I think we should expect the user to kill it first, then set it to failed (which is always possible, even for short retry delays, because a killed task gets held).

**Comment by hjoliver** [comment]
Ah OK, I stand corrected - you linked to the wrong bit of the proposal.

However, my argument above still stands!

The proposal neglects to address the problem of orphaned jobs, which can be avoided simply by requiring a job kill before a state reset (where possible - note I did also state above that we need the ability to force it if the job can't be killed).

**Comment by oliver-sanders** [comment]
This issue covers the mechanism of clock-expiry which is simple and uncontroversial, more significant change will require a new proposal.

**Comment by hjoliver** [comment]
This is closely related, hence I raised it here for discussion.  If it wasn't controversial (I didn't expect it to be) we could simply change the issue title slightly. But fine - I'll shift it to another issue. We don't need a new proposal for every small detail...

**Comment by oliver-sanders** [comment]
The proposal doesn't make mention of the interaction between `clock-expire` and active tasks, possibly oversight, but likely because we assumed continuation of Cylc 7 behaviour here?

One related part of the proposal is point 10:

> Manually triggering a task should not cause an expiry event.
>
> -- https://cylc.github.io/cylc-admin/proposal-optional-output-extension.html#proposal

Suggest tackling that along with this issue rather than shoehorning it into #5640 as the solution will likely overlap.
