### ISSUE TITLE
duplicate output messages

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#6056]
While testing #6046 I noticed we can assign the same output message to different triggers:

```ini
[scheduling]
  [[graph]]
      R1 = "foo:x? & foo:y? => bar"
[runtime]
  [[bar]]
  [[foo]]
     script = "cylc message 'shake n bake'"
     [[[outputs]]]
          x = "shake n bake"
          y = "shake n bake"
```

This ⏫ does the right thing and completes both outputs, but I'm pretty sure it would be a mistake if found in the wild.

You might want to add the fix into #6046 @oliver-sanders ?

**Comment by oliver-sanders** [comment]
We could catch your retro example, but the general solution gets tricky because the message side of the mapping can accept patterns e.g:

```ini
[runtime]
  [[task]]
    [[[outputs]]]
      x = foo .*
      y = .* bar
```

Beyond exhaustively checking whether there is some message that could satisfy both it would be hard to defend against this.

Although it wasn't the intended usage, it could kinda be argued that it's valid for a single message to map onto multiple outputs e.g something like:

```ini
script = """
    cylc message -- data x, y, z written
"""
[[[outputs]]]
  x = data .*x.*  written
  y = data .*y.*  written
  z = data .*z.*  written
```

Surprisingly, there don't presently appear to be any uses of custom outputs at our site, so no pre-existing use cases to constrain us.

**Comment by hjoliver** [comment]
> the message side of the mapping can accept patterns e.g:

That's news to me, which has me doubting my sanity, but from a quick look it doesn't seem to the case.  It's a good idea though!
