### ISSUE TITLE
submit-failed tasks not showing

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#6172]
It has been reported that, following the instructions to reproduce https://github.com/cylc/cylc-flow/issues/6100, submit-failed tasks are not showing in the GUI/Tui.

We are probably missing a data store call (and if we're missing a data store call, we might be missing a database call too?).

**Comment by wxtim** [comment]
## Investigation

`DataStoreMgr.insert_job` looks like it accepts a job state as an argument, because it compares this input against `JOB_STATUS_SET`, passes it to `PbJob`. The name of the method also strongly suggests this.

`TaskEventsMgr._insert_task_jobs` passes `DataStoreMgr.insert_job` a task status. This works by coincidence if the task status is a member of the set of job statuses but is unsafe in the other 3 cases.

```python
(Pdb) TASK_STATUSES_ALL - JOB_STATUS_SET
{'preparing', 'waiting', 'expired'}
(Pdb) JOB_STATUS_SET.intersection(TASK_STATUSES_ALL)
{'succeeded', 'submit-failed', 'failed', 'running', 'submitted'}
``` 

Possible options

1. Can we not add a job state, since we don't have that data? Check that `DataStoreMgr.insert_job` is always followed by a job state update. (`DataStoreMgr.delta_job_state`).
2. Can we check cases where `TaskEventsMgr._insert_task_jobs` is called and legitmately work out job states?

**Comment by oliver-sanders** [comment]
> Can we not add a job state, since we don't have that data

But we do have a job state, it's submit-failed.

Take a look at how submit-failed jobs are created in the store in other parts of the code. We should be able to re-use that approach.

**Comment by wxtim** [comment]
Sorry @oliver-sanders  - this is mostly me using the issue as a place to rubber-duck. 

I forgot to say that at the bottom of my comment as I'd intended.

> > Can we not add a job state, since we don't have that data
> 
> But we do have a job state, it's submit-failed.
> 
> Take a look at how submit-failed jobs are created in the store in other parts of the code. We should be able to re-use that approach.

To clarify - we don't have that data in `TaskEventsMgr._insert_task_jobs` to differentiate different circumstances under which it's called: I've now been away and looked at all the circumstances under which it's called, and am satisfied that this won't be called if the task status is `preparing` or `expired`, and won't be called if it's `waiting` except where the task is waiting for a submission retry.
