### ISSUE TITLE
`cylc vr` bug with `initial cycle point = now`

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#6262]
```ini
[scheduling]
    initial cycle point = now
    [[graph]]
        PT1M = "foo"
[runtime]
    [[foo]]
```

1. `cylc vip bug`
2. `cylc stop bug`
3. (add a comment to `flow.cylc`)
4. `cylc vr bug`

Result:
```
ERROR - Workflow shutting down - InputError: option --icp is not valid for restart
```

This only happens for `initial cycle point = now` 🤔

**Comment by wxtim** [comment]
Duplicated, and assured myself that this is a VR bug - doing this serially as `cylc install` and then `cylc play` is fine.

**Comment by wxtim** [comment]
The problem is that the validate step alters the options object passed to it by storing the value of now as `options.icp`.

I can fix this problem (and any others like it) by copying the options passed to validate, but I wonder if I should stop validate changing options and check that it's not doing this elsewhere?
