### ISSUE TITLE
Intercycle Dependencies not honoured at FCP change & Restart

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#6268]
### Description

Upon changing the final cycle point and restarting a workflow, inter-cycle dependencies on the previous graph are ignored.

### Reproducible Example

```bash
#!/bin/bash
TMP=$(mktemp -d)
echo Files extracted to ${TMP}
mkdir -p "${TMP}"

cat > "${TMP}/./flow.cylc" <<__ICI__
#!jinja2
[scheduler]
    allow implicit tasks = True
    cycle point format = %Y

[scheduling]
    initial cycle point = 1590
    final cycle point = 1591
    [[graph]]
        P1Y = """
            task => fin
            fin[-P1Y] => fin
        """

[runtime]
    [[root]]
        [[[simulation]]]
            default run length = PT0S
__ICI__

WORKFLOW=N"$(uuidgen | awk -F '-' '{print $1}')"

# Run workflow to completion:
cylc vip --no-detach "${TMP}/" --workflow-name "${WORKFLOW}" --mode=simulation

# Modify the fcp
sed -i 's/1591/1593/' "${TMP}/flow.cylc"

# Restart, trigger a task in a new cycle point:
cylc vr "${WORKFLOW}"
cylc trigger --flow=new "${WORKFLOW}//1592/task" --mode=simulation
cylc log "${WORKFLOW}" -m t
```

### Expected Behaviour

The flow will continue from `1592/task` all the way to the new FCP.

**Comment by wxtim** [comment]
My guess is that when you restart with the extended fcp that the task pool doesn't reload proxies for tasks marked succeeded (Why would it?).

**Comment by oliver-sanders** [comment]
I think this may be a duplicate of https://github.com/cylc/cylc-flow/issues/5952

**Comment by wxtim** [comment]
> I think this may be a duplicate of #5952

It is.

**Comment by hjoliver** [comment]
> The behaviour is sort of "intended" under SoD logic, however, totally illogical from the graph perspective.

Meh, reading back through that issue, there is nothing illogical about it.  The root of the problem (in that issue at least; I haven't read this one closely) is that you made a change on restart that affected the structure of the graph - by adding new dependencies on an old (previously succeeded) task.

What happens next depends entirely on whether we think graph execution should be purely event-driven (prerequisites get satisfied when outputs get completed) or not (prerequisites can also get satisfied by output events that happened any time in the past). 

I think we should probably try to implement the latter way, myself, although it's not exactly easy (a lot more DB lookups...) but I suspect it can be argued either way, and neither way is "illogical".

**Comment by oliver-sanders** [comment]
This behaviour flows on from our current implementation of the SoD model, however, this is an implementation choice, not a required (or desired) characteristic of the SoD model so it can only be considered "logical" from the perspective of the implementation, not the model. So personally, I do not think this is arguable that this behaviour is "logical", it does not match either user or developer expectations. Under the current implementation, Cylc can tell you that a task which previously succeeded has not run at all, ignoring its prior history, this is simply a bug, I cannot defend this behaviour.

The SoD implementation is indeed event driven, it's just that those events are not entirely held in memory. We are already looking up outputs every time a task spawns, we do not currently lookup prerequisites (which is completely inconsistent) leading to the bug.

Looking up prerequisites (in addition to outputs) need not add any extra sqlite calls but will increase the "volume" of the calls we are already performing. The performance impacts of this will need to be measured to be determined, however, since the bulk of the heavy lifting is performed at the C layer, I'm cautiously optimistic. To optimise, we can shift as much logical as possible into the SQL query, one optimisation might be to only return prerequisites which are satisfied.

**Comment by hjoliver** [comment]
> We are already looking up outputs every time a task spawns (to prevent "over-running"), we do not currently lookup prerequisites (to prevent "under-running") leading to the bug (which is inconsistent).

The former lookups are an absolute necessity, without which the model would spawn multiple flows at every graph join (`a & b => c`).

The latter are at least arguable. If I add, at runtime, new dependence on on old event, it's not entirely unreasonable to expect that I might have manually fake the old event again to trigger the dependence - because we missed the original event.

This is not merely implementation - the conceptual model itself could be either be event driven in the normal instantaneous sense of the term, or not.

When implementing SoD I did think about this, and ended up with what we've got simply because (a) it is easier not to look up old outputs and unlike the "overrun" case it is not an absolute necessity; and (b) that can be justified conceptually if you favour an instantaneous event-driven model.

That said, I'm being a bit bloody-minded just to object to characterizing the current algorithm as "illogical".  I do agree that we should change it to (in effect) remember past output events.
