### ISSUE TITLE
Improve error message when cylc encounters a missing workflow graph

### ISSUE THREAD

**Issue by uwagura** [cylc/cylc-flow#6343]
### Problem

Due to an error in my Jinja filters, I accidentally tried to run cylc with an empty `[graph]` section. Cylc outputed the following error message:
```
2024-08-29T08:40:07-04:00 INFO - Workflow:  <workflow-name>
2024-08-29T08:40:08-04:00 ERROR - Workflow shutting down - WorkflowConfigError: No workflow dependency graph defined.
ERROR: ERROR: command terminated by signal 1: ssh -oBatchMode=yes -oConnectTimeout=10 -n <node> env CYLC_VERSION=8.3.3 bash --login -c ''"'"'exec "$0" "$@"'"'"'' cylc play <workflow-name> --host=localhost --color=always
```
The first error message was the one that was relevant to solving my problem, but this wasn't immediately apparent to me since cylc highlighted the second error message in red as if it were the fatal error. 
### Proposed Solution

It would be easier to debug workflow issues if we displayed them before or instead of other downstream issues that caused cylc to exit. In particular, the first error message that I received above should have been displayed in red and at the end of the output. This is a minor qualm, and one that users would only encounter if they somehow forget to fill in the dependency graph ( or more likely, made a Jinja mistake like I did), but I think it would make it easier to debug workflow issues by making it clear that the issue is with the workflow itself and not something `ssh` related. This would be especially useful for newer users.

**Comment by hjoliver** [comment]
Hi @uwagura 

Your transcript shows you have `[scheduler][[run hosts]]` configured so `cylc play` tries to re-invoke itself on the remote run host over an ssh connection. There, Cylc aborts with error status because you have no graph defined (Error 1), so ssh reports that the remote command failed (Error 2).

My quick test shows both errors are highlighted in red:

<img width="826" alt="Screenshot 2024-09-02 at 12 02 33 PM" src="https://github.com/user-attachments/assets/d4d0af14-a0c3-4738-825b-15603341c3dd">

Under the circumstances (as just described) it doesn't seem difficult or unreasonable to me look back a couple of lines to see the original cause of the remote play failure.

Also, I'm not sure we could even do what you suggest, because stdout from the remote command comes back over the ssh connection in real time, prior to ssh itself aborting.
 
[Note also if you always validate your workflow locally before playing it, you'll catch errors like this early].

But I'll leave this open for now, to make sure others on the team agree...
