### ISSUE TITLE
when the task ends abnormally(EXIT), cylc gui task status error

### ISSUE THREAD

**Issue by songyeehong** [cylc/cylc-flow#6365]
### Description

Hi, 

I am using the cylc library version is 7.8.11.
There were some tasks that ended abnormally(EXIT) due to hanging error while performing some tasks, exceeding the wall time limit.
> error logs: Exited by LSF signal TERM_RUNLIMIT.

In this case, the task status is not reflected in the GUI and is displayed as 'running(green color)'.
Even if I connected with 'poll' in the cylc gui, LSF job scheduler status(EXIT) is not reflected and is displayed as 'running(green color)'

I wonder if anyone else might have a fix for this problem?

many thanks,
Sonia

**Comment by hjoliver** [comment]
Hi @songyeehong thanks for reaching out. 

Cylc 7.8.11 is very old and we've fixed many hundreds of bugs since then - are you able to upgrade to Cylc 8.3 ?

That said, this is unlikely to be a bug even in Cylc 7.8. It looks like a network issue that prevents job status messages from getting back to the Cylc scheduler.

We might be able to help you track down the problem with 7.8 if you really cannot upgrade, but it would be better to do so on the Cylc forum, at least until we discover an actual bug to post here on GitHub. Are you aware of the forum?: https://cylc.discourse.group

**Comment by songyeehong** [comment]
OK, I will write again on the forum.
Thanks!
